---
version: 2
plan:
  project-key: AJL
  key: FILTRCOMPSPECS
  name: filters-compiler - test
variables:
  dockerNode: adguard/jsl-builder:15.8.0--1.22.5--1

stages:
  - Test:
      manual: 'false'
      final: 'false'
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${bamboo.tmp.directory}/yarn: /usr/local/share/.cache/yarn/v6
    docker-run-arguments:
      - --net=host
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            yarn install
            yarn run test
            chown -R $HOST_UID:$HOST_GID /usr/local/share/.cache/yarn/v6

        environment: HOST_UID='500' HOST_GID='500'
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-qa

labels: []
other:
  concurrent-build-plugin: system-default
