---
version: 2
plan:
  project-key: AJL
  key: FILTRCOMPSPECS
  name: filters-compiler - test
variables:
  dockerNode: adguard/node-ssh:22.17--0

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  other:
    clean-working-dir: true
  docker:
    image: "${bamboo.dockerNode}"
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            pnpm install
            pnpm build
            pnpm lint
            pnpm test
  requirements:
    - adg-docker: 'true'
  final-tasks:
      - script:
          interpreter: SHELL
          scripts:
            - "./bamboo-specs/scripts/cleanup.sh"
branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []
other:
  concurrent-build-plugin: system-default
