---
version: 2
plan:
  project-key: AJL
  key: FILTRCOMPSPECS
  name: filters-compiler - test

stages:
  - Tests:
      manual: false
      final: false
      jobs:
        - Lint
        - Test

Lint:
  key: LINT
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -ex

            # Fix mixed logs
            exec 2>&1

            export DOCKER_BUILDKIT=1

            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg BUILD_RUN_ID=${bamboo.buildNumber} \
              --target lint-output \
              --output type=local,dest=output \
              .
  final-tasks:
    - script: &cleanup-script
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh"
  requirements: &requirements
    - extension: 'true'

Test:
  key: TEST
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -ex

            # Fix mixed logs
            exec 2>&1

            export DOCKER_BUILDKIT=1

            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg BUILD_RUN_ID=${bamboo.buildNumber} \
              --target test-output \
              --output type=local,dest=output \
              .
  final-tasks:
    - script: *cleanup-script
  requirements: *requirements

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

labels: []
other:
  concurrent-build-plugin: system-default
